#!/bin/sh
set -ex

export HOME=/home/buildslave

[ -z "${JENKINS_SLAVE_SSH_PUBKEY}" ] || {
  mkdir ${HOME}/.ssh
  echo "${JENKINS_SLAVE_SSH_PUBKEY}" > ${HOME}/.ssh/authorized_keys
  chown -R buildslave:buildslave ${HOME}/.ssh
  chmod 0700 -R ${HOME}/.ssh
}

ssh-keygen -A

if [ "$1" = "interactive" ]; then
    /usr/sbin/sshd
else
    /usr/sbin/sshd -D
fi
